name: Create Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create temporary directory
      run: |
        mkdir temp_dir

    - name: Copy files to temporary directory
      run: |
        find . -maxdepth 1 -not -name 'temp_dir' -not -name '.' -not -name '.git' -not -name '.github' -exec cp -r {} temp_dir/ \;

    - name: Rename directory
      run: |
        mv temp_dir better-media-manager

    - name: Zip the folder
      run: |
        zip -r better-media-manager-${{ github.event.inputs.tag }}.zip better-media-manager \
        -x "*.git/*" "*.github/*" \
        "better-media-manager/composer.json" "better-media-manager/composer.lock" \
        "better-media-manager/package.json" "better-media-manager/package-lock.json" \
        "better-media-manager/phpstan.neon" "better-media-manager/phpstan-baseline.neon" \
        "better-media-manager/postcss.config.js" "better-media-manager/tailwind.config.js" \
        "better-media-manager/gutenberg-market.php" "better-media-manager/.gitignore" \
        "better-media-manager/webpack.config.js" "better-media-manager/src/*"

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: better-media-manager-${{ github.event.inputs.tag }}.zip
        tag_name: ${{ github.event.inputs.tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write